### ISSUE TITLE
Remove Net::LDAP2 dependency 

### ISSUE THREAD

**Issue by hydrian** [hydrian/TTRSS-Auth-LDAP#12]
Since Net::LDAP2 is being deprecated and is no longer being maintained this plugin needs to implement a new way to do access an LDAP server.

**Comment by chyuaner** [comment]
I use in Ubuntu Server 14.04.2 LTS.
I installed php5-ldap package.
But not work too.

![Imgur](http://i.imgur.com/7Gf8Xx5.png)
<http://imgur.com/7Gf8Xx5>

**Comment by hydrian** [comment]
You also need the php-net-ldap2 package.

**Comment by chyuaner** [comment]
I solved this problem.
I use 'pear' to install Net_LDAP2.
After it work.
<https://pear.php.net/package/Net_LDAP2/>
Thank you! :)

**Comment by nebulade** [comment]
I can confirm, the php-net-ldap2 package seems to be outdated and wont work with this project anymore

**Comment by tsmgeek** [comment]
I have migrated to native PHP LDAP library, #14 fixes this and works on my system.

**Comment by hydrian** [comment]
Closing with commit a7f7a5a82d9202a5c40d606a5c519ba61b224eb8 which removed the Net-LDAP2 dependency.
