### ISSUE TITLE
Plugin does not work anymore since tt-rss moved to PDO

### ISSUE THREAD

**Issue by nmhuy** [hydrian/TTRSS-Auth-LDAP#26]
Hello,

with the plugin enabled, I get the following stack trace:
PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Auth_Ldap::check_password() in /tt-rss/classes/pref/prefs.php:925
Stack trace:
#0 /tt-rss/include/functions.php(1091): Pref_Prefs::isdefaultpassword()
#1 /tt-rss/classes/rpc.php(327): make_init_params()
#2 /tt-rss/backend.php(123): RPC->sanityCheck()
#3 {main}
  thrown in /tt-rss/classes/pref/prefs.php on line 925

Thanks

**Comment by hydrian** [comment]
What is the date of your clone?

**Comment by nmhuy** [comment]
Around July 12th.

**Comment by hydrian** [comment]
Looks like the project added a new required function. I'll look into it.

**Comment by tsimmons** [comment]
Looks like this commit fixes it: https://git.tt-rss.org/git/tt-rss/commit/d0cce0c7a431d886403632ef94add650363d4ef6

**Comment by hydrian** [comment]
Yup. Looks like something in the core broke the auth plugin requirements. It looks to be fixed now. 

@nmhuy I would update your local ttrss core and see if you're still having a problem. If it is still happening, we'll reopen this issue.
