### ISSUE TITLE
ttrss changed Plugin::authenticate

### ISSUE THREAD

**Issue by Waboath** [hydrian/TTRSS-Auth-LDAP#44]
I think the plugin must be rewritten. I don't know with service the auth plugin will be need.

2021/12/30 15:15:11 [error] 13#13: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of Auth_Ldap::authenticate($login, $password) must be compatible with Plugin::authenticate($login, $password, $service = '') in /var/www/html/plugins.local/auth_ldap/init.php on line 225PHP message: PHP Stack trace:PHP message: PHP   1. {main}() /var/www/html/index.php:0PHP message: PHP   2. init_plugins() /var/www/html/index.php:19PHP message: PHP   3. PluginHost->load() /var/www/html/include/functions.php:428PHP message: PHP   4. require_once() /var/www/html/classes/pluginhost.php:476" while reading response header from upstream, client: 172.19.0.14, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "tt-rss"

**Comment by gramakri** [comment]
https://github.com/cloudron-io/TTRSS-Auth-LDAP/commit/a07e42e3e7592a494bd716c3496cd9ba9b8be90b is the fix for this.

**Comment by Waboath** [comment]
Thank you
